
/*******************************************************************************
** PROJECT: 3_Lipocalin 2 and CRC                                              *
** PROGRAM NAME: "Cancer subsites.sas"                                         *
** AUTHOR: Robin Reichmann                                                     *
** SAS-Version: version 9.3_M2                                                 *
** VERSION/DATE: V 1.0 / 2022-01-05                                            *
*                                                                              *
** PURPOSE: Generate subsets of the imputed case-control data for each         *
*  colorectal cancer and subsites outcome                                      *
*                                                                              *
** PROGRAM SPECIFICATION:                                                      *
*  Separate datasets for each colorectal cancer outcome are generated by only  *
*  keeping respective cases and their matched controls.                        *
*                                                                              *
** -PREREQUISITES: macros from SAS macros/Data preparation macros.sas          * 
*                                                                              *
** -READ: lipo_data_RFImputed.csv                                              *
*                                                                              *
** -WRITE: lipo_CC_data.csv                                                    *
*          lipo_CC_prox_data.csv                                               *
*          lipo_CC_dist_data.csv                                               *
*          lipo_RC_data.csv                                                    *
*******************************************************************************/


PROC Import datafile = "C:\lipo_data_RFImputed.csv" out = Lipo_data dbms = csv replace;
  guessingrows = max;
RUN;

PROC Freq data = Lipo_data;
  table Case_Mal_Colon_Dist Case_Mal_Colon_Nos Case_Mal_Colon_Prox Case_Mal_Rectum;
RUN;

DATA Lipo_data; set Lipo_data;
  if Case_Mal_Colon_Dist = 1 or Case_Mal_Colon_Nos = 1 or Case_Mal_Colon_Prox = 1 then
  CC_outcome = 1;
  else CC_outcome = 0;

  if Case_Mal_Colon_Dist = 1 then
  CC_dist_outcome = 1;
  else CC_dist_outcome = 0;

  if Case_Mal_Colon_Prox = 1 then
  CC_prox_outcome = 1;
  else CC_prox_outcome = 0;

  if Case_Mal_Rectum = 1 then
  RC_outcome = 1;
  else RC_outcome = 0;
RUN;

PROC Freq data = Lipo_data;
  table CC_outcome RC_outcome CC_dist_outcome CC_prox_outcome;
RUN;

DATA Lipo_CC_data; set Lipo_data;
  if CACO = 1 and CC_outcome = 0 then delete;
RUN;
DATA Lipo_CC_dist_data; set Lipo_data;
  if CACO = 1 and CC_dist_outcome = 0 then delete;
RUN;
DATA Lipo_CC_prox_data; set Lipo_data;
  if CACO = 1 and CC_prox_outcome = 0 then delete;
RUN;
DATA Lipo_RC_data; set Lipo_data;
  if CACO = 1 and RC_outcome = 0 then delete;
RUN;

%CollectMatches(Data=Lipo_CC_data, OutVar=CC_outcome, MatchVar=Match_Caseset);
%CollectMatches(Data=Lipo_CC_dist_data, OutVar=CC_dist_outcome, MatchVar=Match_Caseset);
%CollectMatches(Data=Lipo_CC_prox_data, OutVar=CC_prox_outcome, MatchVar=Match_Caseset);
%CollectMatches(Data=Lipo_RC_data, OutVar=RC_outcome, MatchVar=Match_Caseset);

PROC Freq data = Lipo_CC_data;
  table CC_outcome;
RUN;
PROC Freq data = Lipo_CC_dist_data;
  table CC_dist_outcome;
RUN;
PROC Freq data = Lipo_CC_prox_data;
  table CC_prox_outcome;
RUN;
PROC Freq data = Lipo_RC_data;
  table RC_outcome;
RUN;

* Export data for IPW in R;
Option missing = "";
PROC Export data = Lipo_CC_data outfile = "C:\lipo_CC_data.csv" DBMS = csv replace;
RUN;
PROC Export data = Lipo_CC_dist_data outfile = "C:\lipo_CC_dist_data.csv" DBMS = csv replace;
RUN;
PROC Export data = Lipo_CC_prox_data outfile = "C:\lipo_CC_prox_data.csv" DBMS = csv replace;
RUN;
PROC Export data = Lipo_RC_data outfile = "C:\lipo_RC_data.csv" DBMS = csv replace;
RUN;
